title: Mayara Stelmaschuk Melo # your name (or website title) here
logo: "/img-may.jpg"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Analyst with 4+ years of experience in analytics and visualization. 
  <br>Currently at Grover.
  <br><br>
  <a href="https://www.mayamelo.com/">mayamelo.com/a> 
  <a href="https://www.linkedin.com/in/maymeelo/">View my LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/maysmelo">View my GitHub Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-YNG2NEMW13 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
