title: Mayara Stelmaschuk Melo # your name (or website title) here
logo: "/master/img-may.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Analyst with 4+ years of experience in analytics and visualization. Currently at Grover.
  <br><br>
  <a href="https://www.linkedin.com/in/maymeelo/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
